#!/bin/bash

# make sure you do the command
# chmod u+x runScript
# run with the command
# nohup ./runScript  &
# It will put its output into a file named nohup.out.

#./part1-t1 is the executable compiled for 1 thread
#./part1-t2 is the executable compiled for 2 threads
#./part1-t4 is the executable compiled for 4 threads, etc.

# These jobs will run one after the other in series, putting the
# information sent to stdout/stderr into the out.* files so you can
# get the execution time results from those files.

#make executables
make --f row_block
make --f row_int
make --f col_block
make --f col_int

#create output files

mkdir outputs

touch outputs/output1_small.txt
touch outputs/output2_small.txt
touch outputs/output4_small.txt
touch outputs/output8_small.txt
touch outputs/output16_small.txt

touch outputs/output1_med.txt
touch outputs/output2_med.txt
touch outputs/output4_med.txt
touch outputs/output8_med.txt
touch outputs/output16_med.txt

touch outputs/output1_large.txt
touch outputs/output2_large.txt
touch outputs/output4_large.txt
touch outputs/output8_large.txt
touch outputs/output16_large.txt

#test on small image

./prog2_rb 2 1 pictures/testimg.jpg test1.jpg >> outputs/output1_small.txt 2>&1
./prog2_rb 2 2 pictures/testimg.jpg test1.jpg >> outputs/output2_small.txt 2>&1
./prog2_rb 2 4 pictures/testimg.jpg test1.jpg >> outputs/output4_small.txt 2>&1
./prog2_rb 2 8 pictures/testimg.jpg test1.jpg >> outputs/output8_small.txt 2>&1
./prog2_rb 2 16 pictures/testimg.jpg test1.jpg >> outputs/output16_small.txt 2>&1

./prog2_cb 2 1 pictures/testimg.jpg test1.jpg >> outputs/output1_small.txt 2>&1
./prog2_cb 2 2 pictures/testimg.jpg test1.jpg >> outputs/output2_small.txt 2>&1
./prog2_cb 2 4 pictures/testimg.jpg test1.jpg >> outputs/output4_small.txt 2>&1
./prog2_cb 2 8 pictures/testimg.jpg test1.jpg >> outputs/output8_small.txt 2>&1
./prog2_cb 2 16 pictures/testimg.jpg test1.jpg >> outputs/output16_small.txt 2>&1

./prog2_ri 2 1 pictures/testimg.jpg test1.jpg >> outputs/output1_small.txt 2>&1
./prog2_ri 2 2 pictures/testimg.jpg test1.jpg >> outputs/output2_small.txt 2>&1
./prog2_ri 2 4 pictures/testimg.jpg test1.jpg >> outputs/output4_small.txt 2>&1
./prog2_ri 2 8 pictures/testimg.jpg test1.jpg >> outputs/output8_small.txt 2>&1
./prog2_ri 2 16 pictures/testimg.jpg test1.jpg >> outputs/output16_small.txt 2>&1

./prog2_ci 2 1 pictures/testimg.jpg test1.jpg >> outputs/output1_small.txt 2>&1
./prog2_ci 2 2 pictures/testimg.jpg test1.jpg >> outputs/output2_small.txt 2>&1
./prog2_ci 2 4 pictures/testimg.jpg test1.jpg >> outputs/output4_small.txt 2>&1
./prog2_ci 2 8 pictures/testimg.jpg test1.jpg >> outputs/output8_small.txt 2>&1
./prog2_ci 2 16 pictures/testimg.jpg test1.jpg >> outputs/output16_small.txt 2>&1

#test on medium image

./prog2_rb 2 1 pictures/leaf.jpg test2.jpg >> outputs/output1_med.txt 2>&1
./prog2_rb 2 2 pictures/leaf.jpg test2.jpg >> outputs/output2_med.txt 2>&1
./prog2_rb 2 4 pictures/leaf.jpg test2.jpg >> outputs/output4_med.txt 2>&1
./prog2_rb 2 8 pictures/leaf.jpg test2.jpg >> outputs/output8_med.txt 2>&1
./prog2_rb 2 16 pictures/leaf.jpg test2.jpg >> outputs/output16_med.txt 2>&1

./prog2_cb 2 1 pictures/leaf.jpg test2.jpg >> outputs/output1_med.txt 2>&1
./prog2_cb 2 2 pictures/leaf.jpg test2.jpg >> outputs/output2_med.txt 2>&1
./prog2_cb 2 4 pictures/leaf.jpg test2.jpg >> outputs/output4_med.txt 2>&1
./prog2_cb 2 8 pictures/leaf.jpg test2.jpg >> outputs/output8_med.txt 2>&1
./prog2_cb 2 16 pictures/leaf.jpg test2.jpg >> outputs/output16_med.txt 2>&1

./prog2_ri 2 1 pictures/leaf.jpg test2.jpg >> outputs/output1_med.txt 2>&1
./prog2_ri 2 2 pictures/leaf.jpg test2.jpg >> outputs/output2_med.txt 2>&1
./prog2_ri 2 4 pictures/leaf.jpg test2.jpg >> outputs/output4_med.txt 2>&1
./prog2_ri 2 8 pictures/leaf.jpg test2.jpg >> outputs/output8_med.txt 2>&1
./prog2_ri 2 16 pictures/leaf.jpg test2.jpg >> outputs/output16_med.txt 2>&1

./prog2_ci 2 1 pictures/leaf.jpg test2.jpg >> outputs/output1_med.txt 2>&1
./prog2_ci 2 2 pictures/leaf.jpg test2.jpg >> outputs/output2_med.txt 2>&1
./prog2_ci 2 4 pictures/leaf.jpg test2.jpg >> outputs/output4_med.txt 2>&1
./prog2_ci 2 8 pictures/leaf.jpg test2.jpg >> outputs/output8_med.txt 2>&1
./prog2_ci 2 16 pictures/leaf.jpg test2.jpg >> outputs/output16_med.txt 2>&1

#test on large image

./prog2_rb 2 1 pictures/peacock.jpg test3.jpg >> outputs/output1_large.txt 2>&1
./prog2_rb 2 2 pictures/peacock.jpg test3.jpg >> outputs/output2_large.txt 2>&1
./prog2_rb 2 4 pictures/peacock.jpg test3.jpg >> outputs/output4_large.txt 2>&1
./prog2_rb 2 8 pictures/peacock.jpg test3.jpg >> outputs/output8_large.txt 2>&1
./prog2_rb 2 16 pictures/peacock.jpg test3.jpg >> outputs/output16_large.txt 2>&1

./prog2_cb 2 1 pictures/peacock.jpg test3.jpg >> outputs/output1_large.txt 2>&1
./prog2_cb 2 2 pictures/peacock.jpg test3.jpg >> outputs/output2_large.txt 2>&1
./prog2_cb 2 4 pictures/peacock.jpg test3.jpg >> outputs/output4_large.txt 2>&1
./prog2_cb 2 8 pictures/peacock.jpg test3.jpg >> outputs/output8_large.txt 2>&1
./prog2_cb 2 16 pictures/peacock.jpg test3.jpg >> outputs/output16_large.txt 2>&1

./prog2_ri 2 1 pictures/peacock.jpg test3.jpg >> outputs/output1_large.txt 2>&1
./prog2_ri 2 2 pictures/peacock.jpg test3.jpg >> outputs/output2_large.txt 2>&1
./prog2_ri 2 4 pictures/peacock.jpg test3.jpg >> outputs/output4_large.txt 2>&1
./prog2_ri 2 8 pictures/peacock.jpg test3.jpg >> outputs/output8_large.txt 2>&1
./prog2_ri 2 16 pictures/peacock.jpg test3.jpg >> outputs/output16_large.txt 2>&1

./prog2_ci 2 1 pictures/peacock.jpg test3.jpg >> outputs/output1_large.txt 2>&1
./prog2_ci 2 2 pictures/peacock.jpg test3.jpg >> outputs/output2_large.txt 2>&1
./prog2_ci 2 4 pictures/peacock.jpg test3.jpg >> outputs/output4_large.txt 2>&1
./prog2_ci 2 8 pictures/peacock.jpg test3.jpg >> outputs/output8_large.txt 2>&1
./prog2_ci 2 16 pictures/peacock.jpg test3.jpg >> outputs/output16_large.txt 2>&1
