#!/bin/bash

#output file
touch output.txt

#test unoptimized version
cp cs338Blur_unopt.cu cs338Blur.cu
echo $'UNOPTIMIZED TEST' > output.txt
echo $'' >> output.txt
#make executables; varies by BLOCK_SIZE
make --f make1
make --f make2
make --f make4
make --f make8
make --f make16
make --f make32
#test on small image
echo $'twotone.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
echo $'tree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/tree.jpg output.jpg >> output.txt
echo $'redtree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
echo $'' >> output.txt

cp cs338Blur_branch.cu cs338Blur.cu
echo $'BRANCH TEST' >> output.txt
echo $'' >> output.txt
#make executables; varies by BLOCK_SIZE
make --f make1
make --f make2
make --f make4
make --f make8
make --f make16
make --f make32
#test on small image
echo $'twotone.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
echo $'tree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/tree.jpg output.jpg >> output.txt
echo $'redtree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
echo $'' >> output.txt

cp cs338Blur_unopt.cu cs338Blur.cu
echo $'OPTIMIZED TEST' >> output.txt
echo $'' >> output.txt
#make executables; varies by BLOCK_SIZE
make --f make1
make --f make2
make --f make4
make --f make8
make --f make16
make --f make32
#test on small image
echo $'twotone.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/twotone.jpg output.jpg >> output.txt
echo $'tree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/tree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/tree.jpg output.jpg >> output.txt
echo $'redtree.jpg' >> output.txt
./cs338Blur_1 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_2 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_4 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_8 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_16 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
./cs338Blur_32 p2_distribute/part1/redtree.jpg output.jpg >> output.txt
echo $'' >> output.txt

#clean up
make --f make1 clean
make --f make2 clean
make --f make4 clean
make --f make8 clean
make --f make16 clean
make --f make32 clean
echo $'finished cleanup' >> output.txt
