#!/bin/bash

#make executables
make --f make_uni
make --f make_bucket
make --f make_indiv
make --f make_local_hists
make --f make_no_locks

#create output files
mkdir outputs

#test on large image
./prog2_big_lock 2 1 pictures/peacock.jpg nulloutput.jpg
./prog2_big_lock 2 2 pictures/peacock.jpg nulloutput.jpg
./prog2_big_lock 2 4 pictures/peacock.jpg nulloutput.jpg
./prog2_big_lock 2 8 pictures/peacock.jpg nulloutput.jpg
./prog2_big_lock 2 16 pictures/peacock.jpg nulloutput.jpg

./prog2_bucket_locks 2 1 pictures/peacock.jpg nulloutput.jpg
./prog2_bucket_locks 2 2 pictures/peacock.jpg nulloutput.jpg
./prog2_bucket_locks 2 4 pictures/peacock.jpg nulloutput.jpg
./prog2_bucket_locks 2 8 pictures/peacock.jpg nulloutput.jpg
./prog2_bucket_locks 2 16 pictures/peacock.jpg nulloutput.jpg

./prog2_indiv_locks 2 1 pictures/peacock.jpg nulloutput.jpg
./prog2_indiv_locks 2 2 pictures/peacock.jpg nulloutput.jpg
./prog2_indiv_locks 2 4 pictures/peacock.jpg nulloutput.jpg
./prog2_indiv_locks 2 8 pictures/peacock.jpg nulloutput.jpg
./prog2_indiv_locks 2 16 pictures/peacock.jpg nulloutput.jpg

./prog2_local_hists 2 1 pictures/peacock.jpg nulloutput.jpg
./prog2_local_hists 2 2 pictures/peacock.jpg nulloutput.jpg
./prog2_local_hists 2 4 pictures/peacock.jpg nulloutput.jpg
./prog2_local_hists 2 8 pictures/peacock.jpg nulloutput.jpg
./prog2_local_hists 2 16 pictures/peacock.jpg nulloutput.jpg

./prog2_no_locks 2 1 pictures/peacock.jpg nulloutput.jpg
./prog2_no_locks 2 2 pictures/peacock.jpg nulloutput.jpg
./prog2_no_locks 2 4 pictures/peacock.jpg nulloutput.jpg
./prog2_no_locks 2 8 pictures/peacock.jpg nulloutput.jpg
./prog2_no_locks 2 16 pictures/peacock.jpg nulloutput.jpg
