#!/bin/bash

#clear old executables
cleanall

#make executables
makeall

#create output directory
mkdir test_outputs

#create output files
touch test_outputs/serial.txt
touch test_outputs/rb.txt
touch test_outputs/ri.txt
touch test_outputs/cb.txt
touch test_outputs/ci.txt
touch test_outputs/opt1.txt
touch test_outputs/opt2.txt
touch test_outputs/opt3.txt

#run executables
./pr-serial >> test_outputs/serial.txt
./pr-parallel-rb >> test_outputs/rb.txt
./pr-parallel-ri >> test_outputs/ri.txt
./pr-parallel-cb >> test_outputs/cb.txt
./pr-parallel-ci >> test_outputs/ci.txt
./pr-parallel-opt1 >> test_outputs/opt1.txt
./pr-parallel-opt2 >> test_outputs/opt2.txt
./pr-parallel-opt3 >> test_outputs/opt3.txt
